server:
  port: 8090 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  profiles:
    active: dev # 环境配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.26:8848 # 服务注册地址
        namespace: 94995f07-6828-445b-9b04-657ffc406c2a # 服务注册的命名空间
      config:
        server-addr: 192.168.101.26:8848 # 注册中心地址
        namespace: 94995f07-6828-445b-9b04-657ffc406c2a # 服务拉取配置的命名空间
        prefix: gateway
        file-extension: yaml # 配置文件格式
        shared-configs: # 共享配置
    gateway:
      discovery:
        locator:
          enabled: true # 自动从配置的服务发现客户端获取服务实例列表
      routes: # 网关路由配置
        - id: management-center
          uri: lb://management-center # 路由的目标地址 lb：loadbalance负载均衡
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/management-center/** # management-center开头的路由转发给management-center服务
